# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Sync Certificates"
  lane :sync_certificates do
    # read-only disables match from overriding the existing certificates.
    match({readonly: true, type: "appstore"})
  end

  desc "Create IPA"
  lane :build do
    # Update profiles and certs
    sync_certificates
    # Increases the build number by 1
    increment_build_number
    # Creates a signed file
    gym
  end

  desc "Upload to TestFlight"
  lane :beta do
    build
    pilot
  end

  desc "Increment Build Number"
  lane :increment do
    increment_build_number
  end
end
