devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE (2nd generation)",
  "iPhone 13 Pro Max",
  "iPad Pro (12.9-inch) (5th generation)"
])

languages([
  "en-US"
])

# scheme("CaseTrackerUITests")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

# For more information about all available options run
# fastlane action snapshot
